spring:
  application:
    name: audio-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dailydictation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://config-server:8880
  servlet:
    multipart:
      max-file-size: 5MB
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #0: no wait for kafka response
      #1: leader write success, not wait for follower
      #-1: wait for all leader, and replication
      acks: -1
      retries: 1
      #spring.kafka.producer.properties.[request.timeout.ms]=1
      #prevent duplicate send
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 3
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      auto-commit-interval: 1000
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
ffmpeg:
  path: C:/ffmpeg/bin/ffmpeg.exe
ffprobe:
  path: C:/ffmpeg/bin/ffprobe.exe
temp:
  audio:
    directory: C:/temp/audio
