spring:
  application:
    name: audio-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dailydictation
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://config-server:8080
  servlet:
    multipart:
      max-file-size: 5MB
